src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\PinRepository;
use Doctrine\ORM\Mapping as ORM;
use Monolog\DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class Pin
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Title can't be blank !")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your first name !")
     * @Assert\Length(
     *      min = 2,
     *      max = 40,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your last name!")
     * @Assert\Length(
     *      min = 2,
     *      max = 40,
     *      minMessage = "Your last name must be at least {{ limit }} characters long",
     *      maxMessage = "Your last name cannot be longer than {{ limit }} characters"
     * )
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Please enter your email")
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 200):string
    {
        return sprintf("https://www.gravatar.com/avatar/%s?s=%d", md5(strtolower((trim($this->getEmail())))),$size);
    }


    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPG or PNG file)',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'Delete ?',
                'download_uri' => true,
                'imagine_pattern'=>'squared_thumbnail_small'
            ])
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
            //   ->add('createdAt')
            //   ->add('updatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
class PinsController extends AbstractController
{

    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/", name="app_home")
     * @param PinRepository $pinRepository
     * @return Response
     */
    public function index(PinRepository $pinRepository): Response
    {
        $pins = $pinRepository->findBy([], ['createdAt' => 'DESC']);
        return $this->render('pins/index.html.twig', compact('pins'));
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_show", methods="GET")
     * @param Pin $pin
     * @param PinRepository $pinRepository
     * @return Response
     */
    public function show(Pin $pin, PinRepository $pinRepository)
    {
        return $this->render('pins/show.html.twig', compact('pin'));
    }


    /**
     * @Route("/pins/create", name="app_pins_create")
     * @Security("is_granted('ROLE_USER') && user.isVerified()")
     * @param Request $request
     * @return Response
     */
    public function create(Request $request)
    {
        $pin = new Pin;
        $form = $this->createForm(PinType::class, $pin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pin->setUser($this->getUser());
            $this->em->persist($pin);
            $this->em->flush();
            $this->addFlash('success','Pin successfully created !!');
            return $this->redirectToRoute('app_home');
        }
        return $this->render('pins/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}/edit", name="app_pins_edit", methods={"GET","PUT"})
     * @IsGranted("PIN_EDIT",subject="pin")
     * @param Pin $pin
     * @param Request $request
     * @return Response
     */
    public function edit(Pin $pin, Request $request): Response
    {
        //   $pin = $pinRepository->findOneBy(['id'=>$id]);
        $form = $this->createForm(PinType::class, $pin, ['method' => 'PUT']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();
            $this->addFlash('success','Pin successfully updated !!');
            return $this->redirectToRoute('app_home');
        }
        return $this->render('pins/edit.html.twig', [
            'pin' => $pin,
            'form' => $form->createView()]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_delete", methods={"DELETE"})
     * @param Pin $pin
     * @param Request $request
     * @return Response
     */
    public function delete(Pin $pin, Request $request): Response
    {
        $this->denyAccessUnlessGranted('PIN_DELETE', $pin);

        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('crsf_token'))) {
            $this->em->remove($pin);
            $this->em->flush();
            $this->addFlash('info','Pin successfully deleted !!');
        }
        return $this->redirectToRoute('app_home');
    }
}

templates/pins/_form.html.twig
{{ form_start(form) }}
        {{ form_widget(form) }}
<input type="submit" value="{{ submitButtonText }}" class="btn btn-primary btn-block" formnovalidate/>
{{ form_end(form) }}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'New pin' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Create Pin</h1>
            {{ include('pins/_form.html.twig', {'submitButtonText': 'Create Pin'}) }}
        </div>
    </div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Edit pin # ' ~ pin.id %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Edit Pin # {{ pin.id }}</h1>
            {{ include('pins/_form.html.twig', { 'submitButtonText': "Update Pin"}) }}
        </div>
    </div>
{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Find all the best pins on erth !' %}

{% block body %}
    {% if pins|length > 0 %}
        <h1 class="text-center text-muted mb-4">{{ pluralize(pins|length, 'Pin', 'Pins') }}</h1>
        {% for row in pins|batch(3) %}
            <div class="row mb-5">
                {% for pin in row %}
                    <div class="col-md-4">
                        <article class="pin bg-white rounded shadow">
                            <div class="mw-100 rounded-top overflow-hidden">
                                <a href="{{ path('app_pins_show', {id:pin.id}) }}">
                                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin): asset('images/placeholder.jpg'))  | imagine_filter('squared_thumbnail_meduim') }}"
                                         alt="{{ pin.title }}" class="w-100">
                                </a>
                            </div>
                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pins_show', {id:pin.id}) }}" class="text-secondary text-decoration-none">
                                    {{ pin.title }}</a></h2>
           {#                 <p>{{ pin.description |u.truncate(20, '...', false) }} </p>
                            <p>Created at {{ pin.createdAt |date }} </p>
                            <p>Submitted {{ pin.createdAt |ago }} </p>#}
                            <p class="pb-3 pl-3 text-muted"><small>Submitted {{ pin.user.fullName }}</small></p>
                        </article>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="h1 mt-5 text-center">No pins yet. <a href="{{ path('app_pins_create') }}">Be the first!</a></p>
    {% endif %}

{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title %}

{% block body %}
    <div class="row">
        <div class="col-md-6 m-auto">
            <article class="pin bg-white rounded shadow">
                <div class="mw-100 rounded-top overflow-hidden">
                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin): asset('images/placeholder.jpg'))  | imagine_filter('squared_thumbnail_meduim') }}"
                         alt="{{ pin.title }}" class="w-100">
                </div>
                <div class="p-3">
                    <h1 class="h5 text-secondary">{{ pin.title }}</h1>
                    <p class=" text-muted">
                        <small>
                            Submitted
                            <time datetime="{{ pin.createdAt|date('Y-m-d H:i:s') }}">
                                {{ pin.createdAt|ago }}
                            </time>
                            by {{ pin.user.fullName }}
                        </small>
                    </p>
                    <p class="pt-3 text-break">{{ pin.description }} </p>
                    {% if (is_granted('PIN_EDIT', pin) or is_granted('PIN_DELETE', pin))%}
                    <div class="pt-3">
                        <a href="{{ path('app_pins_edit', {id:pin.id}) }}" class="btn btn-light">Edit</a>
                        <a href="#"
                           onclick="event.preventDefault();confirm('Are you confirm ?') && document.getElementById('js-delete-form').submit();"
                           class="btn btn-light">Delete</a>
                        <form id="js-delete-form" action="{{ path('app_pins_delete', {id:pin.id}) }}" method="post"
                              style="display: none">
                            <input type="hidden" name="crsf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id) }}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
{% endblock %}